### ISSUE TITLE
Modification to BIP79

### ISSUE THREAD

**Issue by NicolasDorier** [RHavar/bustapay#1] opened 2020-02-26 05:07 UTC
We are implementing that at BTCPay level (see https://github.com/btcpayserver/btcpayserver/pull/1321#issuecomment-591240204)

```csharp
So there is two thing that bother me with the general approach:

Using a hotwallet is not very safe, also, allowing payjoin also mean that a customer can enumerate the utxos of the merchant. So payjoin has a form of disutility to it.

As such, I think it should be a different payment method on which the merchant can charge an extra network cost for this disutility. But with the current UX, this is an impossible thing to do.

One way would be to modify BIP79 to allow the merchant to set up extra fee.
```

Would you agree to change your implementation and BIP79 to support such parameter?

**Comment by RHavar** [comment] 2020-03-04 20:55
So let's separate the different "attacks" and discuss possible mitigations:

---

**a) The abort attack**

In this attack, and attacker creates a template-transaction, gives it to the merchant, and then abort the process by double-spending the template-transaction (since the template transaction isn't broadcasted by the bitcoin network, it's not a double-spend from the bitcoin network point of view).

The abort attack is detectible by the merchant, and costs the attacker 1 utxo.  There are some possible mitigations:

a1) The merchant realizes that someone has spied on some of their wallet, so are extra careful about it (e.g. mix it, reuse it) 

a2) The merchant guesses someone is trying to do an abort attack (even probabilistically) and propagates the template transaction. This stops the attacker from being able to abort the process, and go through something (e.g. make a payment) they didn't really want to even do



**b) The sneaky spy attack**

The attacker does a *successful* bip79 payment to a merchant, and (silently) records the utxos the merchant has. This is undetectable from the merchants point of view. It's worth noting this problem exists with normal bitcoin payments (if i pay a merchant, i can watch that utxo to see what the merchant does with it) but bip79 exacerbates it.

Mitigations:

b1) merchant is careful with what utxo they contribute for bip79
b2) merchant only offers bip79 for higher value transactions
b3) merchant charges an extra fee for doing a bip79 payment

---



So AFAICT the only one that really needs a protocol change would be mitigation b3 (to stop b style attack). Is this really so desired to justify the complexity? I strongly feel at the moment that the answer is no. Pining @Kukks  as it looks like he's doing some bip79 stuff, in case he wants to add anything

**Comment by Kukks** [comment] 2020-03-05 18:20
I'm also against added complexity, at least for the time being.

**Comment by RHavar** [comment] 2020-03-05 18:26
Cool, I'm going to close this for now. I think in summary:

The current 1-utxo-cost is going to be good enough now that pretty much no merchants need to worry (the calculus might be a bit different for some high-interest targets like darknet markets, where people are prepared to spend real money to get extra info)

And I think in the near term, mitigations a2) and b2) are  the most powerful, quite easy to do and require no protocol changes.

**Closed as completed by RHavar** 2020-03-05 18:26 UTC

**Comment by Kukks** [comment] 2020-03-05 18:29
The BIP79 implementation I've done so far broadcasts the template transaction after `x` time IF:
* the payjoin tx has not been broadcasted
* the payjoin tx was broadcasted but has RBF signalled and has noticed a double spend attempt taht removes the payjoin tx from the mempool. 

In any case, when a payjoin tx is not broadcasted and confirmed, the exposed utxos are placed in a prioritized bucket for the next payjoin. 


How do you handle RBF from your end? 

Also with regards to mitigation a2, if the abort attack happens with a higher fee, the template transaction broadcast threat won't be very effective against the abuser, no?

**Comment by Kukks** [comment] 2020-03-05 18:31
Unless I actively pay to parent after broadcasting the template transaction to bump the fee that way.

**Comment by RHavar** [comment] 2020-03-05 22:07
> Unless I actively pay to parent after broadcasting the template transaction to bump the fee that way.

Depending on circumstances, perhaps a clever way might be to "pin" their template-transaction so they can't RBF it. 

So hypothetically say someone gives you a template-transaction and you suspect they're going to abort-attack you. And the transaction is RBF, what you do is broadcast their template-transaction *AND* immediately do a *HUGE* consolidation-like transaction (e.g. 0.1 MB worth at 1 sat/byte) that sources the template-transaction.

Now that the template-transaction is pinned, trying to RBF it would cost them quite a bit of money (because of the restrictive rules of bip125)
